export default {
  // 프로필
  profilecut: "/profile/profilecut.webp",
  profilecut2: "/profile/profilecut2.webp",
  profilecut4: "/profile/profilecut4.webp",

  // 영화
  넷플릭스: "/icons/netflix.jpg",
  유튜브: "/icons/유튜브.jpg",
  티빙: "/icons/티빙.png",
  왓챠: "/icons/watcha.webp",
  웨이브: "/icons/wavve.png",
  시리즈온: "/icons/시리즈온.png",
  유플러스: "/icons/uplus.webp",
  댓글부대: "/movie_poster/댓글부대p.webp",
  정말먼곳: "/movie_poster/정말먼곳p.webp",
  청설: "/movie_poster/청설p.webp",
  결백: "/movie_poster/결백p.webp",
  보이스: "/movie_poster/보이스p.webp",
  공개예정: "/movie_poster/공개예정.png",

  // 라디오
  radio1: "/radio/이금희.png",
  radio2: "/radio/약한영웅.png",
  radio3: "/radio/악귀.png",
  radio4: "/radio/댓글부대.png",
  radio5: "/radio/청설.png",
  SBS: "/radio/SBS.jpg",
  KBS: "/radio/KBS.jpg",
  //mv
  mv1: "/mv/옥탑방에서.png",
  mv2: "/mv/태연뮤비.png",
  mv3: "/mv/내일의우리.png",
  비스킷타운: "/mv/비스킷타운.jpg",
  SM: "/mv/SMTOWN.jpg",
  카더가든: "/mv/카더가든.jpg",
  //ad
  스니커즈: "/ad/스니커즈.jpg",
  LG: "/ad/LG.jpg",
  데상트: "/ad/데상트.jpg",
  소니: "/ad/SONY.jpg",
  맥심: "/ad/맥심.jpg",
  어나더오피스: "/ad/어나더오피스.jpg",

  // 좋아하는 영화
  굿타임: "/favourites_movie/굿타임.jpg",
  나의아름다운세탁소: "/favourites_movie/나의아름다운세탁소.jpg",
  나의왼발: "/favourites_movie/나의왼발.jpg",
  남매의여름밤: "/favourites_movie/남매의여름밤.jpg",
  너의새는노래할수있어: "/favourites_movie/너의새는노래할수있어.webp",
  네멋대로해라: "/favourites_movie/네멋대로해라.jpg",
  다크나이트: "/favourites_movie/다크나이트.jpg",
  대니쉬걸: "/favourites_movie/대니쉬걸.jpg",
  더킹: "/favourites_movie/더킹.webp",
  데어윌비블러드: "/favourites_movie/데어윌비블러드.jpg",
  리코리쉬피자: "/favourites_movie/리코리쉬피자.jpg",
  마미: "/favourites_movie/마미.jpg",
  마스터: "/favourites_movie/마스터.jpg",
  마티아스와막심: "/favourites_movie/마티아스와 막심.jpg",
  매그놀리아: "/favourites_movie/매그놀리아.webp",
  머니볼: "/favourites_movie/머니볼.jpg",
  메이디셈버: "/favourites_movie/메이디셈버.jpg",
  몽상가들: "/favourites_movie/몽상가들.jpg",
  복수는나의것: "/favourites_movie/복수는나의것.jpg",
  블루발렌타인: "/favourites_movie/블루발렌타인.jpg",
  사랑에대한모든것: "/favourites_movie/사랑에대한모든것.jpg",
  사랑은낙엽을타고: "/favourites_movie/사랑은낙엽을타고.webp",
  성실한나라의앨리스: "/favourites_movie/성실한나라의앨리스.jpg",
  세비지그레이스: "/favourites_movie/세비지그레이스.jpg",
  소년적니: "/favourites_movie/소년적니.jpg",
  아이킬드마이마더: "/favourites_movie/아이킬드마이마더.jpg",
  악은존재하지않는다: "/favourites_movie/악은존재하지않는다.jpg",
  어느멋진아침: "/favourites_movie/어느멋진아침.jpg",
  언컷젬스: "/favourites_movie/언컷젬스.jpg",
  엘리펀트송: "/favourites_movie/엘리펀트송.jpg",
  외계인2부: "/favourites_movie/외계인2부.webp",
  전망좋은방: "/favourites_movie/전망좋은방.jpg",
  지옥: "/favourites_movie/지옥.jpg",
  천국의그림자: "/favourites_movie/천국의그림자.jpg",
  콜미바이유어네임: "/favourites_movie/콜미바이유어네임.webp",
  탐엣더팜: "/favourites_movie/탐엣더팜.jpg",
  테넷: "/favourites_movie/테넷.jpg",
  팬텀스레드: "/favourites_movie/팬텀스레드.webp",
  펀치드링크러브: "/favourites_movie/펀치드렁크러브.webp",
  폭스캐처: "/favourites_movie/폭스캐처.webp",
  플라워킬링문: "/favourites_movie/플라워킬링문.jpg",
  해피아워: "/favourites_movie/해피 아워.webp",
  만추: "/favourites_movie/만추.jpg",
  로렌스애니웨이: "/favourites_movie/로렌스애니웨이.jpg",
};
