export const images = {
  // 프로필
  profilecut: "/profile/profilecut.webp",
  profilecut2: "/profile/profilecut2.webp",
  profilecut4: "/profile/profilecut4.webp",

  // 영화
  넷플릭스: "/icons/netflix.jpg",
  유튜브: "/icons/유튜브.jpg",
  티빙: "/icons/티빙.png",
  왓챠: "/icons/watcha.webp",
  웨이브: "/icons/wavve.png",
  시리즈온: "/icons/시리즈온.png",
  유플러스: "/icons/uplus.webp",
  댓글부대: "/movie_poster/댓글부대p.webp",
  정말먼곳: "/movie_poster/정말먼곳p.webp",
  청설: "/movie_poster/청설p.webp",
  결백: "/movie_poster/결백p.webp",
  보이스: "/movie_poster/보이스p.webp",
  공개예정: "/movie_poster/공개예정.png",
  all: "/icons/all.png",
  twel: "/icons/12.png",
  fift: "/icons/15.png",
  ninet: "/icons/19.svg",

  // 라디오
  radio1: "/radio/이금희.png",
  radio2: "/radio/약한영웅.png",
  radio3: "/radio/악귀.png",
  radio4: "/radio/댓글부대.png",
  radio5: "/radio/청설.png",
  SBS: "/radio/SBS.jpg",
  KBS: "/radio/KBS.jpg",
  //mv
  mv1: "/mv/옥탑방에서.png",
  mv2: "/mv/태연뮤비.png",
  mv3: "/mv/내일의우리.png",
  비스킷타운: "/mv/비스킷타운.jpg",
  SM: "/mv/SMTOWN.jpg",
  카더가든: "/mv/카더가든.jpg",
  //ad
  스니커즈: "/ad/스니커즈.jpg",
  LG: "/ad/LG.jpg",
  데상트: "/ad/데상트.jpg",
  소니: "/ad/SONY.jpg",
  맥심: "/ad/맥심.jpg",
  어나더오피스: "/ad/어나더오피스.jpg",

  // 좋아하는 영화
  굿타임: "/favourites_movie/굿타임.jpg",
  나의아름다운세탁소: "/favourites_movie/나의아름다운세탁소.jpg",
  네멋대로해라: "/favourites_movie/네멋대로해라.jpg",
  다크나이트: "/favourites_movie/다크나이트.jpg",
  마미: "/favourites_movie/마미.jpg",
  마스터: "/favourites_movie/마스터.jpg",
  마티아스와막심: "/favourites_movie/마티아스와 막심.jpg",
  매그놀리아: "/favourites_movie/매그놀리아.webp",
  머니볼: "/favourites_movie/머니볼.jpg",
  메이디셈버: "/favourites_movie/메이디셈버.jpg",
  복수는나의것: "/favourites_movie/복수는나의것.jpg",
  블루발렌타인: "/favourites_movie/블루발렌타인.jpg",
  아이킬드마이마더: "/favourites_movie/아이킬드마이마더.jpg",
  어느멋진아침: "/favourites_movie/어느멋진아침.jpg",
  전망좋은방: "/favourites_movie/전망좋은방.jpg",
  지옥: "/favourites_movie/지옥.jpg",
  천국의그림자: "/favourites_movie/천국의그림자.jpg",
  탐엣더팜: "/favourites_movie/탐엣더팜.jpg",
  만추: "/favourites_movie/만추.jpg",
  로렌스애니웨이: "/favourites_movie/로렌스애니웨이.jpg",
};
