import images from "@/app/assets/images";

const moviesData = [
  {
    id: 1,
    poster: images.결백,
    title: "매그놀리아",
    content: "",
    cast: "",
    director: "폴 토마스 앤더슨",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 2,
    poster: images.펀치드렁크러브,
    title: "펀치 드렁크 러브",
    content: "",
    cast: "",
    director: "폴 토마스 앤더슨",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 3,
    poster: images.팬텀스레드,
    title: "팬텀 스레드",
    content: "",
    cast: "",
    director: "폴 토마스 앤더슨",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 4,
    poster: images.외계인2부,
    title: "외계+인 2부",
    content: "",
    cast: "",
    director: "최동훈",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 5,
    poster: images.해피아워,
    title: "해피 아워",
    content: "",
    cast: "",
    director: "하마구치 류스케",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 6,
    poster: images.너의새는노래할수있어,
    title: "너의 새는 노래할 수 있어",
    content: "",
    cast: "",
    director: "미야케 쇼",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 7,
    poster: images.천국의그림자,
    title: "천국의 그림자",
    content: "",
    cast: "",
    director: "아키카우리스마키",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 8,
    poster: images.사랑은낙엽을타고,
    title: "사랑은 낙엽을 타고",
    content: "",
    cast: "",
    director: "아키카우리스마키",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 9,
    poster: images.블루발렌타인,
    title: "블루 발렌타인",
    content: "",
    cast: "",
    director: "데릭 시엔 프랜스",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 10,
    poster: images.더킹헨리5세,
    title: "더 킹: 헨리 5세",
    content: "",
    cast: "",
    director: "데이비드 미쇼",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 11,
    poster: images.머니볼,
    title: "머니볼",
    content: "",
    cast: "",
    director: "베넷 밀러",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 12,
    poster: images.폭스캐쳐,
    title: "폭스 캐쳐",
    content: "",
    cast: "",
    director: "베넷 밀러",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 13,
    poster: images.지옥,
    title: "지옥",
    content: "",
    cast: "",
    director: "클로드 샤브롤",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 14,
    poster: images.콜미바이유어네임,
    title: "콜 미 바이 유어 네임",
    content: "",
    cast: "",
    director: "루카 구아다니노",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 15,
    poster: images.다크나이트,
    title: "다크나이트",
    content: "",
    cast: "",
    director: "크리스토퍼 놀란",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 16,
    poster: images.성실한나라의앨리스,
    title: "성실한 나라의 앨리스",
    content: "",
    cast: "",
    director: "안국진",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 17,
    poster: images.복수는나의것,
    title: "복수는 나의 것",
    content: "",
    cast: "",
    director: "이마무라 쇼헤이",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 18,
    poster: images.굿타임,
    title: "굿타임",
    content: "",
    cast: "",
    director: "사프디 형제",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 19,
    poster: images.언컷젬스,
    title: "언컷 젬스",
    content: "",
    cast: "",
    director: "사프디 형제",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 20,
    poster: images.테넷,
    title: "테넷",
    content: "",
    cast: "",
    director: "크리스토퍼 놀란",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 21,
    poster: images.소년적니,
    title: "소년적니",
    content: "",
    cast: "",
    director: "증국상",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 22,
    poster: images.남매의여름밤,
    title: "남매의 여름밤",
    content: "",
    cast: "",
    director: "윤단비",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 23,
    poster: images.악은존재하지않는다,
    title: "악은 존재하지 않는다",
    content: "",
    cast: "",
    director: "하마구치 류스케",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 24,
    poster: images.네멋대로해라,
    title: "네 멋대로 해라",
    content: "",
    cast: "",
    director: "장 뤽 고다르",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 25,
    poster: images.몽상가들,
    title: "몽상가들",
    content: "",
    cast: "",
    director: "베르나르도 베르톨루치",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 26,
    poster: images.어느멋진아침,
    title: "어느 멋진 아침",
    content: "",
    cast: "",
    director: "미아 한센-러브",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 27,
    poster: images.로렌스애니웨이,
    title: "로렌스 애니웨이",
    content: "",
    cast: "",
    director: "자비에 돌란",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 28,
    poster: images.탐엣더팜,
    title: "탐엣더팜",
    content: "",
    cast: "",
    director: "자비에 돌란",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 29,
    poster: images.엘리펀트송,
    title: "엘리펀트 송",
    content: "",
    cast: "",
    director: "찰스 비나메",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 30,
    poster: images.아이라킬드마이마더,
    title: "아이 킬드 마이 마더",
    content: "",
    cast: "",
    director: "자비에 돌란",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 31,
    poster: images.마티아스와막심,
    title: "마티아스와 막심",
    content: "",
    cast: "",
    director: "자비에 돌란",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 32,
    poster: images.마미,
    title: "마미",
    content: "",
    cast: "",
    director: "자비에 돌란",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 33,
    poster: images.마스터,
    title: "마스터",
    content: "",
    cast: "",
    director: "폴 토마스 앤더슨",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 34,
    poster: images.리코리쉬피자,
    title: "리코리쉬 피자",
    content: "",
    cast: "",
    director: "폴 토마스 앤더슨",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 35,
    poster: images.데어윌비블러드,
    title: "데어 윌 비 블러드",
    content: "",
    cast: "",
    director: "폴 토마스 앤더슨",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 36,
    poster: images.나의원발,
    title: "나의 원발",
    content: "",
    cast: "",
    director: "짐 쉐리단",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 37,
    poster: images.전망좋은방,
    title: "전망 좋은 방",
    content: "",
    cast: "",
    director: "제임스 아이보리",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 38,
    poster: images.나의아름다운세탁소,
    title: "나의 아름다운 세탁소",
    content: "",
    cast: "",
    director: "스티븐 프리어스",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 39,
    poster: images.플라워킬링문,
    title: "플라워 킬링 문",
    content: "",
    cast: "",
    director: "마틴 스코 세이지",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 40,
    poster: images.메이디셈버,
    title: "메이 디셈버",
    content: "",
    cast: "",
    director: "토드 헤인즈",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 41,
    poster: images.세비지그레이스,
    title: "세비지 그레이스",
    content: "",
    cast: "",
    director: "톰 칼린",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 42,
    poster: images.사랑에대한모든것,
    title: "사랑에 대한 모든 것",
    content: "",
    cast: "",
    director: "제임스 마쉬",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 43,
    poster: images.대니쉬걸,
    title: "대니쉬 걸",
    content: "",
    cast: "",
    director: "톰 후퍼",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
  {
    id: 44,
    poster: images.만추,
    title: "만추",
    content: "",
    cast: "",
    director: "김태용",
    genre: "",
    category: ["공개예정"],
    platforms: [],
    trailers: [],
  },
];
export default moviesData;
